"""
Django settings for Shatalito project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-=!#tu_clave_secreta_aqui#@!' # ¡CAMBIA ESTO EN PRODUCCIÓN!

DEBUG = True # Déjalo True por ahora para desarrollo

ALLOWED_HOSTS = []

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'caja', # App principal para manejar la caja
    'rest_framework', # Django REST Framework para APIs
    'cliente', # App para manejar clientes
    'cocina', # App para manejar cocina
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware', # Importante para la seguridad de formularios y AJAX
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # Directorio de plantillas a nivel de proyecto
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

FIXTURE_DIRS = [
    os.path.join(BASE_DIR, 'fixtures'),  # Directorio para fixtures
]

AUTH_PASSWORD_VALIDATORS = [
    # ... (puedes dejarlos por defecto o configurarlos)
]

# Modelo de Usuario Personalizado
AUTH_USER_MODEL = 'caja.CustomUser'

LANGUAGE_CODE = 'es-ar' # Español Argentina
TIME_ZONE = 'America/Argentina/Buenos_Aires' # Tu zona horaria
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_prod') # Para 'collectstatic' en producción

MEDIA_URL = '/media/' # URL base para servir archivos multimedia (imágenes de productos)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # Directorio donde se almacenan los archivos multimedia

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# URLs de redirección para el sistema de autenticación
LOGIN_URL = 'caja:login'
LOGOUT_REDIRECT_URL = 'caja:login'
LOGIN_REDIRECT_URL = 'caja:determine_dashboard'  # Redirige al dashboard después de iniciar sesión

# Configuración de correo
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'alda.rojas.99@gmail.com'  # info@shatalito.com.ar
EMAIL_HOST_PASSWORD = 'mpahkshivxvbhrdp'  # App Password de shatalito
DEFAULT_FROM_EMAIL = 'Shatalito <info@shatalito.com.ar'
EMAIL_TO = 'alda.rojas.99@gmail.com' #contacto@shatalito.com.ar contacto global