# Generated by Django 5.2.1 on 2025-06-10 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_category_paymentmethod_paymentstatus_promotion_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='order',
            name='initialTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 10, 23, 6, 55, 508271, tzinfo=datetime.timezone.utc)),
        ),
    ]
