# Generated by Django 5.2.1 on 2025-06-10 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_remove_order_total_amount_alter_order_initialtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price_at_time_of_order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='initialTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 10, 23, 46, 42, 564748, tzinfo=datetime.timezone.utc)),
        ),
    ]
