# Generated by Django 5.2.1 on 2025-06-12 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_remove_orderitem_price_at_time_of_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='subtotal',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='order',
            name='initialTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 12, 22, 48, 56, 165206, tzinfo=datetime.timezone.utc)),
        ),
    ]
