# Generated by Django 5.2.1 on 2025-06-12 23:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_rename_subtotal_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='initialTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 12, 23, 6, 42, 372191, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='caja.order'),
        ),
    ]
