# Generated by Django 5.2.1 on 2025-06-12 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0006_orderitem_subtotal_alter_order_initialtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='initialTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 12, 23, 19, 36, 535630, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
