# Generated by Django 5.2.5 on 2025-08-28 19:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0008_alter_order_initialtime_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Empleado', 'Empleado'), ('Administrador', 'Administrador'), ('Super Usuario', 'Super Usuario'), ('cocinero', 'Cocinero')], default='Empleado', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='initialTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 28, 19, 54, 58, 508139, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to='caja.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/products/'),
        ),
    ]
