# Generated by Django 5.2.5 on 2025-10-21 19:14

from django.db import migrations
from django.core.management import call_command

def load_fixture(apps, schema_editor):
    call_command('loaddata', 'default_data.json')

class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0009_alter_customuser_role_alter_order_initialtime_and_more'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
