# Generated by Django 5.2.1 on 2025-10-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0010_order_payment_status_order_preference_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='preference_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
