# Generated by Django 5.2.1 on 2025-11-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0011_order_customer_email_alter_order_initialtime_and_more'),
        ('caja', '0011_remove_order_payment_status_and_more'),
    ]

    operations = [
    ]
