# Generated by Django 5.2.1 on 2025-11-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0012_merge_20251115_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='observations',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
