# Generated by Django 5.2.3 on 2025-11-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0013_order_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
